// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/files/complete": {
            "post": {
                "description": "Verifies uploaded files on R2, stores file metadata, and registers the upload session in the database. Each transfer is valid for 1 hour and limited to 100MB for anonymous uploads.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Complete file upload",
                "parameters": [
                    {
                        "description": "Upload completion payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CompleteUploadInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Files uploaded successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Payload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input or verification failed",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    }
                }
            }
        },
        "/api/v1/files/presign": {
            "post": {
                "description": "Accepts a list of files (name and size), validates the total size, and returns presigned PUT URLs for each file. Each upload session is identified by a unique token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Generate presigned URLs for file upload",
                "parameters": [
                    {
                        "description": "List of files to upload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "filename": {
                                        "type": "string"
                                    },
                                    "size": {
                                        "type": "integer"
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Presigned URLs generated successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Payload"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.PresignResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input or size limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    },
                    "500": {
                        "description": "Failed to generate presigned URL",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    }
                }
            }
        },
        "/api/v1/share/{token}": {
            "get": {
                "description": "Returns metadata (name, size, contentType, index) of all files in a shared transfer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Share"
                ],
                "summary": "Retrieve shared file details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Share token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Files retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid token",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    },
                    "404": {
                        "description": "Invalid or expired share link",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    },
                    "410": {
                        "description": "Share link has expired",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    }
                }
            }
        },
        "/api/v1/share/{token}/presign-download/{index}": {
            "get": {
                "description": "Returns a temporary signed URL to download a specific file (by index) from a shared transfer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Share"
                ],
                "summary": "Generate a presigned download URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Share token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "File index",
                        "name": "index",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Presigned download URL generated successfully",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    },
                    "404": {
                        "description": "File not found or invalid share link",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    },
                    "410": {
                        "description": "Share link has expired",
                        "schema": {
                            "$ref": "#/definitions/utils.Payload"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CompleteUploadInput": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "contentType": {
                                "type": "string"
                            },
                            "filename": {
                                "type": "string"
                            },
                            "key": {
                                "type": "string"
                            },
                            "size": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "handlers.PresignResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "urls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.PresignedFile"
                    }
                }
            }
        },
        "handlers.PresignedFile": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "uploadURL": {
                    "type": "string"
                }
            }
        },
        "utils.Payload": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
